with (obj_roomsettings_name)
    instance_destroy()
with (obj_roomsettings_close)
    instance_destroy()
with (obj_roomsettings_musicprev)
    instance_destroy()
with (obj_roomsettings_musicnext)
    instance_destroy()
with (obj_roomsettings_size)
    instance_destroy()
