function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 1; // obj_miniufo_laser
	global.__objectDepths[1] = 0; // obj_robotknife
	global.__objectDepths[2] = 0; // obj_spitcheesespike
	global.__objectDepths[3] = 0; // obj_banditochicken
	global.__objectDepths[4] = 0; // obj_bigcheese
	global.__objectDepths[5] = 0; // obj_cheeserobot
	global.__objectDepths[6] = 0; // obj_cheeseslime
	global.__objectDepths[7] = 0; // obj_forknight
	global.__objectDepths[8] = 0; // obj_miniufo
	global.__objectDepths[9] = 0; // obj_peasanto
	global.__objectDepths[10] = 0; // obj_pizzaball
	global.__objectDepths[11] = 0; // obj_pizzaboy
	global.__objectDepths[12] = 0; // obj_pizzagoblin
	global.__objectDepths[13] = 0; // obj_robot
	global.__objectDepths[14] = 0; // obj_spitcheese
	global.__objectDepths[15] = 0; // obj_baddie
	global.__objectDepths[16] = 0; // obj_baddiecollisionbox
	global.__objectDepths[17] = 0; // obj_baddiedead
	global.__objectDepths[18] = 0; // obj_baddiegibs
	global.__objectDepths[19] = 0; // obj_sausageman_dead
	global.__objectDepths[20] = 0; // obj_bigdestructibles
	global.__objectDepths[21] = 0; // obj_destructibles
	global.__objectDepths[22] = 0; // obj_forkhitbox
	global.__objectDepths[23] = 0; // obj_parryhitbox
	global.__objectDepths[24] = 10; // obj_platform
	global.__objectDepths[25] = 0; // obj_slaphitbox
	global.__objectDepths[26] = 10; // obj_slope
	global.__objectDepths[27] = 10; // obj_slopeleft
	global.__objectDepths[28] = 10; // obj_sloperight
	global.__objectDepths[29] = 0; // obj_swordhitbox
	global.__objectDepths[30] = 10; // obj_wall
	global.__objectDepths[31] = -1000; // obj_camera
	global.__objectDepths[32] = -1000; // obj_debugcontroller
	global.__objectDepths[33] = 0; // obj_init
	global.__objectDepths[34] = 0; // obj_music
	global.__objectDepths[35] = 2000; // obj_parallax
	global.__objectDepths[36] = -99; // obj_particlesystem
	global.__objectDepths[37] = -9990; // obj_pause
	global.__objectDepths[38] = -15; // obj_playerOLD
	global.__objectDepths[39] = 0; // obj_room
	global.__objectDepths[40] = -1000; // obj_tv
	global.__objectDepths[41] = 5; // obj_bombexplosion
	global.__objectDepths[42] = -6; // obj_endlevelfade
	global.__objectDepths[43] = 0; // obj_hurtbox
	global.__objectDepths[44] = -9999; // obj_rank
	global.__objectDepths[45] = 0; // obj_thunder
	global.__objectDepths[46] = 10; // obj_timesup
	global.__objectDepths[47] = -9999; // obj_transition
	global.__objectDepths[48] = 2; // obj_bigcollect
	global.__objectDepths[49] = 2; // obj_collect
	global.__objectDepths[50] = 2; // obj_collect_escape
	global.__objectDepths[51] = 2; // obj_key
	global.__objectDepths[52] = 2; // obj_pizzakincheese
	global.__objectDepths[53] = 2; // obj_pizzakinpineapple
	global.__objectDepths[54] = 2; // obj_pizzakinsausage
	global.__objectDepths[55] = 2; // obj_pizzakinshroom
	global.__objectDepths[56] = 2; // obj_pizzakintomato
	global.__objectDepths[57] = 2; // obj_pizzaslice
	global.__objectDepths[58] = 3; // obj_treasure
	global.__objectDepths[59] = 3; // obj_treasurecollect
	global.__objectDepths[60] = 0; // obj_breakabledoor
	global.__objectDepths[61] = 1; // obj_desertdestroyable
	global.__objectDepths[62] = 1; // obj_destroyable
	global.__objectDepths[63] = 1; // obj_destroyable_escape
	global.__objectDepths[64] = 1; // obj_destroyable2
	global.__objectDepths[65] = 1; // obj_destroyable2_big
	global.__objectDepths[66] = 1; // obj_destroyable2_big_escape
	global.__objectDepths[67] = 1; // obj_destroyable2_escape
	global.__objectDepths[68] = 1; // obj_destroyable3
	global.__objectDepths[69] = 1; // obj_destroyable3_escape
	global.__objectDepths[70] = 2; // obj_glassblock
	global.__objectDepths[71] = 0; // obj_metalblock
	global.__objectDepths[72] = 0; // obj_metalblock_escape
	global.__objectDepths[73] = 11; // obj_onewayblock
	global.__objectDepths[74] = 11; // obj_onewayblock_escape
	global.__objectDepths[75] = 0; // obj_pizzaballblock
	global.__objectDepths[76] = 2; // obj_ballgoal
	global.__objectDepths[77] = 2; // obj_balloon
	global.__objectDepths[78] = 2; // obj_bomb
	global.__objectDepths[79] = 0; // obj_cheeseblock
	global.__objectDepths[80] = 0; // obj_dashpad
	global.__objectDepths[81] = 0; // obj_exitdoorsign
	global.__objectDepths[82] = 2; // obj_goalsign
	global.__objectDepths[83] = 11; // obj_ladder
	global.__objectDepths[84] = 0; // obj_minipillar
	global.__objectDepths[85] = 5; // obj_pinballlauncher
	global.__objectDepths[86] = 0; // obj_railh
	global.__objectDepths[87] = 0; // obj_railh2
	global.__objectDepths[88] = 0; // obj_railv
	global.__objectDepths[89] = 0; // obj_reverseminipillar
	global.__objectDepths[90] = 0; // obj_spike
	global.__objectDepths[91] = 0; // obj_swordstone
	global.__objectDepths[92] = 6; // obj_teleporter
	global.__objectDepths[93] = 6; // obj_teleporterend
	global.__objectDepths[94] = 0; // obj_timedgate
	global.__objectDepths[95] = 2; // obj_timedgateclock
	global.__objectDepths[96] = 0; // obj_tomatoblock
	global.__objectDepths[97] = 3; // obj_door
	global.__objectDepths[98] = 0; // obj_doorA
	global.__objectDepths[99] = 0; // obj_doorB
	global.__objectDepths[100] = 0; // obj_doorC
	global.__objectDepths[101] = 0; // obj_doorD
	global.__objectDepths[102] = 0; // obj_doorE
	global.__objectDepths[103] = 2; // obj_exitgate
	global.__objectDepths[104] = 0; // obj_hallwayleft
	global.__objectDepths[105] = 0; // obj_hallwayright
	global.__objectDepths[106] = 3; // obj_keydoor
	global.__objectDepths[107] = 3; // obj_roomdoor
	global.__objectDepths[108] = 3; // obj_startgate
	global.__objectDepths[109] = 0; // obj_controls
	global.__objectDepths[110] = 0; // obj_levelselect
	global.__objectDepths[111] = 0; // obj_mainmenu
	global.__objectDepths[112] = 0; // obj_option
	global.__objectDepths[113] = 0; // obj_quitprompt
	global.__objectDepths[114] = 0; // obj_rockcutscene
	global.__objectDepths[115] = 0; // obj_title
	global.__objectDepths[116] = 0; // obj_titlecutscene
	global.__objectDepths[117] = -2; // obj_debris
	global.__objectDepths[118] = -2; // obj_glassdebris
	global.__objectDepths[119] = -7; // obj_knightdebris
	global.__objectDepths[120] = -2; // obj_metaldebris
	global.__objectDepths[121] = 0; // obj_panicdebris
	global.__objectDepths[122] = 0; // obj_pizzaloss
	global.__objectDepths[123] = -2; // obj_slapstar
	global.__objectDepths[124] = -4; // obj_slimedebris
	global.__objectDepths[125] = -2; // obj_wooddebris
	global.__objectDepths[126] = 0; // obj_balloonpop
	global.__objectDepths[127] = 0; // obj_bangeffect
	global.__objectDepths[128] = -7; // obj_bulletimpact
	global.__objectDepths[129] = 0; // obj_bumpeffect
	global.__objectDepths[130] = 0; // obj_chargeeffect
	global.__objectDepths[131] = -6; // obj_cloudeffect
	global.__objectDepths[132] = 0; // obj_dashcloud
	global.__objectDepths[133] = 0; // obj_explosioneffect
	global.__objectDepths[134] = 0; // obj_highjumpcloud
	global.__objectDepths[135] = 0; // obj_jumpdust
	global.__objectDepths[136] = -6; // obj_landcloud
	global.__objectDepths[137] = -4; // obj_mach2effect
	global.__objectDepths[138] = -4; // obj_mach3effect
	global.__objectDepths[139] = 0; // obj_machalleffect
	global.__objectDepths[140] = 0; // obj_punchdust
	global.__objectDepths[141] = 0; // obj_slidecloud
	global.__objectDepths[142] = 0; // obj_spikehurteffect
	global.__objectDepths[143] = 0; // obj_stompeffect
	global.__objectDepths[144] = 0; // obj_superdashcloud
	global.__objectDepths[145] = -10; // obj_superslameffect
	global.__objectDepths[146] = 1; // obj_taunteffect
	global.__objectDepths[147] = 0; // obj_enemybird
	global.__objectDepths[148] = 0; // obj_smallnumber
	global.__objectDepths[149] = 0; // obj_uparrow
	global.__objectDepths[150] = 0; // obj_null


	global.__objectNames[0] = "obj_miniufo_laser";
	global.__objectNames[1] = "obj_robotknife";
	global.__objectNames[2] = "obj_spitcheesespike";
	global.__objectNames[3] = "obj_banditochicken";
	global.__objectNames[4] = "obj_bigcheese";
	global.__objectNames[5] = "obj_cheeserobot";
	global.__objectNames[6] = "obj_cheeseslime";
	global.__objectNames[7] = "obj_forknight";
	global.__objectNames[8] = "obj_miniufo";
	global.__objectNames[9] = "obj_peasanto";
	global.__objectNames[10] = "obj_pizzaball";
	global.__objectNames[11] = "obj_pizzaboy";
	global.__objectNames[12] = "obj_pizzagoblin";
	global.__objectNames[13] = "obj_robot";
	global.__objectNames[14] = "obj_spitcheese";
	global.__objectNames[15] = "obj_baddie";
	global.__objectNames[16] = "obj_baddiecollisionbox";
	global.__objectNames[17] = "obj_baddiedead";
	global.__objectNames[18] = "obj_baddiegibs";
	global.__objectNames[19] = "obj_sausageman_dead";
	global.__objectNames[20] = "obj_bigdestructibles";
	global.__objectNames[21] = "obj_destructibles";
	global.__objectNames[22] = "obj_forkhitbox";
	global.__objectNames[23] = "obj_parryhitbox";
	global.__objectNames[24] = "obj_platform";
	global.__objectNames[25] = "obj_slaphitbox";
	global.__objectNames[26] = "obj_slope";
	global.__objectNames[27] = "obj_slopeleft";
	global.__objectNames[28] = "obj_sloperight";
	global.__objectNames[29] = "obj_swordhitbox";
	global.__objectNames[30] = "obj_wall";
	global.__objectNames[31] = "obj_camera";
	global.__objectNames[32] = "obj_debugcontroller";
	global.__objectNames[33] = "obj_init";
	global.__objectNames[34] = "obj_music";
	global.__objectNames[35] = "obj_parallax";
	global.__objectNames[36] = "obj_particlesystem";
	global.__objectNames[37] = "obj_pause";
	global.__objectNames[38] = "obj_playerOLD";
	global.__objectNames[39] = "obj_room";
	global.__objectNames[40] = "obj_tv";
	global.__objectNames[41] = "obj_bombexplosion";
	global.__objectNames[42] = "obj_endlevelfade";
	global.__objectNames[43] = "obj_hurtbox";
	global.__objectNames[44] = "obj_rank";
	global.__objectNames[45] = "obj_thunder";
	global.__objectNames[46] = "obj_timesup";
	global.__objectNames[47] = "obj_transition";
	global.__objectNames[48] = "obj_bigcollect";
	global.__objectNames[49] = "obj_collect";
	global.__objectNames[50] = "obj_collect_escape";
	global.__objectNames[51] = "obj_key";
	global.__objectNames[52] = "obj_pizzakincheese";
	global.__objectNames[53] = "obj_pizzakinpineapple";
	global.__objectNames[54] = "obj_pizzakinsausage";
	global.__objectNames[55] = "obj_pizzakinshroom";
	global.__objectNames[56] = "obj_pizzakintomato";
	global.__objectNames[57] = "obj_pizzaslice";
	global.__objectNames[58] = "obj_treasure";
	global.__objectNames[59] = "obj_treasurecollect";
	global.__objectNames[60] = "obj_breakabledoor";
	global.__objectNames[61] = "obj_desertdestroyable";
	global.__objectNames[62] = "obj_destroyable";
	global.__objectNames[63] = "obj_destroyable_escape";
	global.__objectNames[64] = "obj_destroyable2";
	global.__objectNames[65] = "obj_destroyable2_big";
	global.__objectNames[66] = "obj_destroyable2_big_escape";
	global.__objectNames[67] = "obj_destroyable2_escape";
	global.__objectNames[68] = "obj_destroyable3";
	global.__objectNames[69] = "obj_destroyable3_escape";
	global.__objectNames[70] = "obj_glassblock";
	global.__objectNames[71] = "obj_metalblock";
	global.__objectNames[72] = "obj_metalblock_escape";
	global.__objectNames[73] = "obj_onewayblock";
	global.__objectNames[74] = "obj_onewayblock_escape";
	global.__objectNames[75] = "obj_pizzaballblock";
	global.__objectNames[76] = "obj_ballgoal";
	global.__objectNames[77] = "obj_balloon";
	global.__objectNames[78] = "obj_bomb";
	global.__objectNames[79] = "obj_cheeseblock";
	global.__objectNames[80] = "obj_dashpad";
	global.__objectNames[81] = "obj_exitdoorsign";
	global.__objectNames[82] = "obj_goalsign";
	global.__objectNames[83] = "obj_ladder";
	global.__objectNames[84] = "obj_minipillar";
	global.__objectNames[85] = "obj_pinballlauncher";
	global.__objectNames[86] = "obj_railh";
	global.__objectNames[87] = "obj_railh2";
	global.__objectNames[88] = "obj_railv";
	global.__objectNames[89] = "obj_reverseminipillar";
	global.__objectNames[90] = "obj_spike";
	global.__objectNames[91] = "obj_swordstone";
	global.__objectNames[92] = "obj_teleporter";
	global.__objectNames[93] = "obj_teleporterend";
	global.__objectNames[94] = "obj_timedgate";
	global.__objectNames[95] = "obj_timedgateclock";
	global.__objectNames[96] = "obj_tomatoblock";
	global.__objectNames[97] = "obj_door";
	global.__objectNames[98] = "obj_doorA";
	global.__objectNames[99] = "obj_doorB";
	global.__objectNames[100] = "obj_doorC";
	global.__objectNames[101] = "obj_doorD";
	global.__objectNames[102] = "obj_doorE";
	global.__objectNames[103] = "obj_exitgate";
	global.__objectNames[104] = "obj_hallwayleft";
	global.__objectNames[105] = "obj_hallwayright";
	global.__objectNames[106] = "obj_keydoor";
	global.__objectNames[107] = "obj_roomdoor";
	global.__objectNames[108] = "obj_startgate";
	global.__objectNames[109] = "obj_controls";
	global.__objectNames[110] = "obj_levelselect";
	global.__objectNames[111] = "obj_mainmenu";
	global.__objectNames[112] = "obj_option";
	global.__objectNames[113] = "obj_quitprompt";
	global.__objectNames[114] = "obj_rockcutscene";
	global.__objectNames[115] = "obj_title";
	global.__objectNames[116] = "obj_titlecutscene";
	global.__objectNames[117] = "obj_debris";
	global.__objectNames[118] = "obj_glassdebris";
	global.__objectNames[119] = "obj_knightdebris";
	global.__objectNames[120] = "obj_metaldebris";
	global.__objectNames[121] = "obj_panicdebris";
	global.__objectNames[122] = "obj_pizzaloss";
	global.__objectNames[123] = "obj_slapstar";
	global.__objectNames[124] = "obj_slimedebris";
	global.__objectNames[125] = "obj_wooddebris";
	global.__objectNames[126] = "obj_balloonpop";
	global.__objectNames[127] = "obj_bangeffect";
	global.__objectNames[128] = "obj_bulletimpact";
	global.__objectNames[129] = "obj_bumpeffect";
	global.__objectNames[130] = "obj_chargeeffect";
	global.__objectNames[131] = "obj_cloudeffect";
	global.__objectNames[132] = "obj_dashcloud";
	global.__objectNames[133] = "obj_explosioneffect";
	global.__objectNames[134] = "obj_highjumpcloud";
	global.__objectNames[135] = "obj_jumpdust";
	global.__objectNames[136] = "obj_landcloud";
	global.__objectNames[137] = "obj_mach2effect";
	global.__objectNames[138] = "obj_mach3effect";
	global.__objectNames[139] = "obj_machalleffect";
	global.__objectNames[140] = "obj_punchdust";
	global.__objectNames[141] = "obj_slidecloud";
	global.__objectNames[142] = "obj_spikehurteffect";
	global.__objectNames[143] = "obj_stompeffect";
	global.__objectNames[144] = "obj_superdashcloud";
	global.__objectNames[145] = "obj_superslameffect";
	global.__objectNames[146] = "obj_taunteffect";
	global.__objectNames[147] = "obj_enemybird";
	global.__objectNames[148] = "obj_smallnumber";
	global.__objectNames[149] = "obj_uparrow";
	global.__objectNames[150] = "obj_null";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
